heart = load('rec_1m.mat');
t = 0:0.002:20-0.002;
figure(1);
plot(t,heart.val(1,:));
xlabel('Time(sec)');
ylabel('Voltage NF');
figure(2);
plot(t,heart.val(2,:));
xlabel('Time(sec)');
ylabel('Voltage F');
figure(3);
plot(t(1:1000),heart.val(1,1:1000));
figure(4);
plot(t(1:1000),heart.val(2,1:1000));
fs = 500; %Sampling frequency
%xFft = linspace(1000, fs/2, numel(heart.val(1,:)));
%xFft1=(0:length(heart.val(1,:))-1)*fs/(length(heart.val(1,:)));
xFft1=(-length(heart.val(1,:))/2:length(heart.val(1,:))/2-1)*(fs/length(heart.val(1,:)));
yFft1 = fft(heart.val(1,:)); 
yFft1 = fftshift(yFft1); 
figure(5);
plot(xFft1, abs(yFft1));
xlabel('Frequency(Hz)');
ylabel('Power NF');
%xFft2=(0:length(heart.val(2,:))-1)*fs/(length(heart.val(2,:)));
xFft2=(-length(heart.val(2,:))/2:length(heart.val(2,:))/2-1)*(fs/length(heart.val(2,:)));
yFft2 = fft(heart.val(2,:)); 
yFft2 = fftshift(yFft2); 
figure(6);
plot(xFft2, abs(yFft2));
xlabel('Frequency(Hz)');
ylabel('Power F');