tmin = 0;
tmax = 10;
dt = (tmax - tmin)/1000;
time = tmin:dt:tmax;
f = 2;
y = cos(2*pi*f*time);
figure(1);
plot(time,y);
xlabel('time');
ylabel('Y');
title('Cosine func in time domain');
fs = 1/dt;
%xfreq = linspace(-fs/2,fs/2,numel(y));
xfreq=(0:length(y)-1)*fs/(length(y));
yfreq = fft(y);
figure(2);
plot(xfreq,yfreq);
xlabel('Frequency');
ylabel('YFreq');
title('Cosine func in frequency domain(not shifted)');
yfreq = fftshift(yfreq);
xfreq=(-length(y)/2:length(y)/2-1)*(fs/length(y));
figure(3);
plot(xfreq,yfreq);
xlabel('Frequency');
ylabel('YFreq');
title('Cosine func in frequency domain(shifted)');
